name: Build ImmortalWrt for PSG1218

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev git

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure target
      run: |
        echo "CONFIG_TARGET_ramips=y" > .config
        echo "CONFIG_TARGET_ramips_mt7620=y" >> .config
        echo "CONFIG_TARGET_ramips_mt7620_DEVICE_psg1218=y" >> .config
        make defconfig

    - name: Build firmware
      run: make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: bin/targets/ramips/mt7620/
